// <auto-generated />
using System;
using BlazorECommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240603211959_NewProductVariantsAdded")]
    partial class NewProductVariantsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorECommerce.Shared.CartItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId", "ProductTypeId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Featured = false,
                            Icon = "bi bi-rocket",
                            Name = "Science-Fiction",
                            Url = "science-fiction"
                        },
                        new
                        {
                            Id = 2,
                            Featured = false,
                            Icon = "bi bi-magic",
                            Name = "Fantasy",
                            Url = "fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Featured = false,
                            Icon = "bi bi-heart-arrow",
                            Name = "Romance",
                            Url = "romance"
                        },
                        new
                        {
                            Id = 4,
                            Featured = false,
                            Icon = "bi bi-lightning",
                            Name = "Thriller",
                            Url = "thriller"
                        },
                        new
                        {
                            Id = 5,
                            Featured = false,
                            Icon = "bi bi-person-badge",
                            Name = "Biography",
                            Url = "biography"
                        },
                        new
                        {
                            Id = 6,
                            Featured = false,
                            Icon = "bi bi-balloon",
                            Name = "Children",
                            Url = "children"
                        },
                        new
                        {
                            Id = 7,
                            Featured = false,
                            Icon = "bi bi-journal-richtext",
                            Name = "Classic",
                            Url = "classic"
                        },
                        new
                        {
                            Id = 8,
                            Featured = false,
                            Icon = "bi bi-egg-fried",
                            Name = "Cooking",
                            Url = "cooking"
                        },
                        new
                        {
                            Id = 9,
                            Featured = false,
                            Icon = "bi bi-heart-pulse",
                            Name = "Health & Fitness",
                            Url = "health-fitness"
                        },
                        new
                        {
                            Id = 10,
                            Featured = false,
                            Icon = "bi bi-brush",
                            Name = "Art",
                            Url = "art"
                        },
                        new
                        {
                            Id = 11,
                            Featured = false,
                            Icon = "bi bi-lightbulb",
                            Name = "Science",
                            Url = "science"
                        },
                        new
                        {
                            Id = 12,
                            Featured = false,
                            Icon = "bi bi-walking",
                            Name = "Sport",
                            Url = "sport"
                        },
                        new
                        {
                            Id = 13,
                            Featured = false,
                            Icon = "bi bi-emoji-dizzy",
                            Name = "Horror",
                            Url = "horror"
                        },
                        new
                        {
                            Id = 14,
                            Featured = false,
                            Icon = "bi bi-patch-check",
                            Name = "Self-Help",
                            Url = "self-help"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quanity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId", "ProductTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neuromancer is a science fiction novel by American-Canadian writer William Gibson, published in 1984.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4b/Neuromancer_%28Book%29.jpg",
                            Title = "Neuromancer",
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Snow Crash is a science fiction novel by American writer Neal Stephenson, published in 1992.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d5/Snowcrash.jpg",
                            Title = "Snow Crash",
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Foundation is a science fiction novel by American writer Isaac Asimov, first published in 1951.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/25/Foundation_gnome.jpg",
                            Title = "Foundation",
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Brave New World is a dystopian social science fiction novel by English author Aldous Huxley, published in 1932.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/62/BraveNewWorld_FirstEdition.jpg",
                            Title = "Brave New World",
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hyperion is a science fiction novel by American author Dan Simmons, published in 1989.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a1/Hyperion_cover.jpg",
                            Title = "Hyperion",
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ender's Game is a 1985 military science fiction novel by American author Orson Scott Card.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/95/Ender%27s_Game_cover_ISBN_0312932081.jpg",
                            Title = "Ender's Game",
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "The Martian is a 2011 science fiction novel written by Andy Weir.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c3/The_Martian_2014.jpg",
                            Title = "The Martian",
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Left Hand of Darkness is a science fiction novel by U.S. writer Ursula K. Le Guin, published in 1969.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/29/TheLeftHandOfDarkness1stEd.jpg",
                            Title = "The Left Hand of Darkness",
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Stranger in a Strange Land is a 1961 science fiction novel by American author Robert A. Heinlein.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/84/StrangerInaStrangeLand_Cover.jpg",
                            Title = "Stranger in a Strange Land",
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Do Androids Dream of Electric Sheep? is a science fiction novel by American writer Philip K. Dick, published in 1968.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/ee/DoAndroidsDream.png",
                            Title = "Do Androids Dream of Electric Sheep?",
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "The Road is a 2006 novel by American writer Cormac McCarthy. It is a post-apocalyptic story of a father and his young son.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6b/The-road.jpg",
                            Title = "The Road",
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/dc/The_Hunger_Games.jpg",
                            Title = "The Hunger Games",
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ready Player Two is a 2020 science fiction novel by American author Ernest Cline.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/Ready_Player_Two.jpg",
                            Title = "Ready Player Two",
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Fahrenheit 451 is a 1953 dystopian novel by American writer Ray Bradbury.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/db/Fahrenheit_451_1st_ed_cover.jpg",
                            Title = "Fahrenheit 451",
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "The Handmaid's Tale is a dystopian novel by Canadian author Margaret Atwood, published in 1985.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/ba/TheHandmaidsTale.jpg",
                            Title = "The Handmaid's Tale",
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Altered Carbon is a 2002 science fiction novel by the English author Richard K. Morgan.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/b5/Altered_Carbon_%28cover%29.jpg",
                            Title = "Altered Carbon",
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            Description = "Leviathan Wakes is a science fiction novel by James S. A. Corey, the first book in The Expanse series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/03/Leviathan_Wakes.jpg",
                            Title = "The Expanse: Leviathan Wakes",
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            Description = "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg",
                            Title = "The Hobbit",
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            Description = "A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels by American author George R. R. Martin.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/93/AGameOfThrones.jpg",
                            Title = "A Game of Thrones",
                            Views = 0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J.K. Rowling.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg",
                            Title = "Harry Potter and the Philosopher's Stone",
                            Views = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "The Way of Kings is an epic fantasy novel written by American author Brandon Sanderson.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/TheWayOfKings.png",
                            Title = "The Way of Kings",
                            Views = 0
                        },
                        new
                        {
                            Id = 23,
                            Description = "Mistborn: The Final Empire is a fantasy novel written by American author Brandon Sanderson.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6d/Mistborn-cover.jpg",
                            Title = "Mistborn: The Final Empire",
                            Views = 0
                        },
                        new
                        {
                            Id = 24,
                            Description = "The Lies of Locke Lamora is a fantasy novel by American writer Scott Lynch.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4c/The_Lies_of_Locke_Lamora.jpg",
                            Title = "The Lies of Locke Lamora",
                            Views = 0
                        },
                        new
                        {
                            Id = 25,
                            Description = "Uprooted is a fantasy novel written by Naomi Novik.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a7/Uprooted_book_cover.jpg",
                            Title = "Uprooted",
                            Views = 0
                        },
                        new
                        {
                            Id = 26,
                            Description = "Circe is a 2018 novel by American writer Madeline Miller.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4b/Circe-novel.jpg",
                            Title = "Circe",
                            Views = 0
                        },
                        new
                        {
                            Id = 27,
                            Description = "The Night Circus is a fantasy novel by Erin Morgenstern.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a5/TheNightCircus.jpg",
                            Title = "The Night Circus",
                            Views = 0
                        },
                        new
                        {
                            Id = 28,
                            Description = "Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch is a 1990 novel written by Neil Gaiman and Terry Pratchett.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/1d/GoodOmensCover.jpg",
                            Title = "Good Omens",
                            Views = 0
                        },
                        new
                        {
                            Id = 29,
                            Description = "American Gods is a fantasy novel by British author Neil Gaiman.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/American_Gods.jpg",
                            Title = "American Gods",
                            Views = 0
                        },
                        new
                        {
                            Id = 30,
                            Description = "The Ocean at the End of the Lane is a 2013 novel by British author Neil Gaiman.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4e/Ocean_at_the_End_of_the_Lane_US_cover.jpg",
                            Title = "The Ocean at the End of the Lane",
                            Views = 0
                        },
                        new
                        {
                            Id = 31,
                            Description = "The Color of Magic is a 1983 fantasy novel by British writer Terry Pratchett, the first book in his Discworld series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Colour_of_Magic_%28cover_art%29.jpg",
                            Title = "The Color of Magic",
                            Views = 0
                        },
                        new
                        {
                            Id = 32,
                            Description = "Mort is a fantasy novel by British writer Terry Pratchett, the fourth book in his Discworld series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/Mort_%28Terry_Pratchett_novel_-_cover_art%29.jpg",
                            Title = "Mort",
                            Views = 0
                        },
                        new
                        {
                            Id = 33,
                            Description = "Small Gods is the thirteenth of Terry Pratchett's Discworld novels, published in 1992.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8c/Smallgods.jpg",
                            Title = "Small Gods",
                            Views = 0
                        },
                        new
                        {
                            Id = 34,
                            Description = "Guards! Guards! is a fantasy novel by British writer Terry Pratchett, the eighth book in his Discworld series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/20/Guards-Guards-cover.jpg",
                            Title = "Guards! Guards!",
                            Views = 0
                        },
                        new
                        {
                            Id = 35,
                            Description = "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg",
                            Title = "The Hobbit",
                            Views = 0
                        },
                        new
                        {
                            Id = 36,
                            Description = "The Fellowship of the Ring is the first of three volumes of the epic novel The Lord of the Rings by the English author J. R. R. Tolkien.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif",
                            Title = "The Fellowship of the Ring",
                            Views = 0
                        },
                        new
                        {
                            Id = 37,
                            Description = "The Two Towers is the second volume of J.R.R. Tolkien's high-fantasy novel The Lord of the Rings.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a1/The_Two_Towers_cover.gif",
                            Title = "The Two Towers",
                            Views = 0
                        },
                        new
                        {
                            Id = 38,
                            Description = "The Return of the King is the third and final volume of J.R.R. Tolkien's The Lord of the Rings.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/11/The_Return_of_the_King_cover.gif",
                            Title = "The Return of the King",
                            Views = 0
                        },
                        new
                        {
                            Id = 39,
                            Description = "The Silmarillion is a collection of mythopoeic works by English writer J. R. R. Tolkien, edited and published posthumously by his son, Christopher Tolkien.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/The_Silmarillion_first_edition.jpg",
                            Title = "The Silmarillion",
                            Views = 0
                        },
                        new
                        {
                            Id = 40,
                            Description = "The Catcher in the Rye is a novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/32/Rye_catcher.jpg",
                            Title = "The Catcher in the Rye",
                            Views = 0
                        },
                        new
                        {
                            Id = 41,
                            Description = "To Kill a Mockingbird is a novel by Harper Lee published in 1960.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/7/79/To_Kill_a_Mockingbird.JPG",
                            Title = "To Kill a Mockingbird",
                            Views = 0
                        },
                        new
                        {
                            Id = 42,
                            Description = "Nineteen Eighty-Four, often referred to as 1984, is a dystopian social science fiction novel by the English writer George Orwell.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c3/1984first.jpg",
                            Title = "1984",
                            Views = 0
                        },
                        new
                        {
                            Id = 44,
                            Description = "Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Title_page_of_Pride_and_Prejudice%2C_the_first_edition.jpg/800px-Title_page_of_Pride_and_Prejudice%2C_the_first_edition.jpg",
                            Title = "Pride and Prejudice",
                            Views = 0
                        },
                        new
                        {
                            Id = 45,
                            Description = "Moby-Dick; or, The Whale is an 1851 novel by American writer Herman Melville.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/57/Moby-Dick_FE_title_page.jpg",
                            Title = "Moby-Dick",
                            Views = 0
                        },
                        new
                        {
                            Id = 46,
                            Description = "The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/TheGreatGatsby_1925jacket.jpeg/800px-TheGreatGatsby_1925jacket.jpeg",
                            Title = "The Great Gatsby",
                            Views = 0
                        },
                        new
                        {
                            Id = 47,
                            Description = "War and Peace is a novel by the Russian author Leo Tolstoy, published from 1865 to 1869.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/8b/War-and-peace-book-cover.jpg",
                            Title = "War and Peace",
                            Views = 0
                        },
                        new
                        {
                            Id = 48,
                            Description = "Dune is a science fiction novel by American author Frank Herbert, originally published in 1965.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a8/Dune_1965_First_Edition.jpg",
                            Title = "Dune",
                            Views = 0
                        },
                        new
                        {
                            Id = 49,
                            Description = "Jane Eyre is a novel by English writer Charlotte Brontë, published under the pen name \"Currer Bell\", on 16 October 1847.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Jane_Eyre_title_page.jpg/800px-Jane_Eyre_title_page.jpg",
                            Title = "Jane Eyre",
                            Views = 0
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductCategories", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paperback"
                        },
                        new
                        {
                            Id = 3,
                            Name = "E-Book"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audiobook"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 2,
                            OriginalPrice = 19.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 4,
                            OriginalPrice = 29.99m,
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 2,
                            OriginalPrice = 14.99m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 2.99m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 2,
                            OriginalPrice = 29.99m,
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 3,
                            OriginalPrice = 24.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductTypeId = 1,
                            OriginalPrice = 299m,
                            Price = 159.99m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductTypeId = 1,
                            OriginalPrice = 399m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = 12,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 14,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 16,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 17,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 18,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 22,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 23,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 24,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 25,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 27,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 28,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 29,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 30,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 31,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 32,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 33,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 34,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 35,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 36,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 37,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 38,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 39,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 40,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 41,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 42,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 44,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 45,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 46,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 47,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 48,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 49,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.OrderItem", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductCategories", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductVariant", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
