// <auto-generated />
using System;
using BlazorECommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorECommerce.Shared.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.CartItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId", "ProductTypeId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Featured = false,
                            Icon = "<g><rect fill=\"none\" height=\"24\" width=\"24\"/></g><g><path d=\"M19.8,18.4L14,10.67V6.5l1.35-1.69C15.61,4.48,15.38,4,14.96,4H9.04C8.62,4,8.39,4.48,8.65,4.81L10,6.5v4.17L4.2,18.4 C3.71,19.06,4.18,20,5,20h14C19.82,20,20.29,19.06,19.8,18.4z\"/></g>",
                            Name = "Science-Fiction",
                            Url = "science-fiction"
                        },
                        new
                        {
                            Id = 2,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M7.5 5.6L10 7 8.6 4.5 10 2 7.5 3.4 5 2l1.4 2.5L5 7zm12 9.8L17 14l1.4 2.5L17 19l2.5-1.4L22 19l-1.4-2.5L22 14zM22 2l-2.5 1.4L17 2l1.4 2.5L17 7l2.5-1.4L22 7l-1.4-2.5zm-7.63 5.29c-.39-.39-1.02-.39-1.41 0L1.29 18.96c-.39.39-.39 1.02 0 1.41l2.34 2.34c.39.39 1.02.39 1.41 0L16.7 11.05c.39-.39.39-1.02 0-1.41l-2.33-2.35zm-1.03 5.49l-2.12-2.12 2.44-2.44 2.12 2.12-2.44 2.44z\"/>",
                            Name = "Fantasy",
                            Url = "fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z\"/>",
                            Name = "Romance",
                            Url = "romance"
                        },
                        new
                        {
                            Id = 4,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M7 2v11h3v9l7-12h-4l4-8z\"/>",
                            Name = "Thriller",
                            Url = "thriller"
                        },
                        new
                        {
                            Id = 5,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z\"/>",
                            Name = "Biography",
                            Url = "biography"
                        },
                        new
                        {
                            Id = 6,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><circle cx=\"14.5\" cy=\"10.5\" r=\"1.25\"/><circle cx=\"9.5\" cy=\"10.5\" r=\"1.25\"/><path d=\"M22.94 12.66c.04-.21.06-.43.06-.66s-.02-.45-.06-.66c-.25-1.51-1.36-2.74-2.81-3.17-.53-1.12-1.28-2.1-2.19-2.91C16.36 3.85 14.28 3 12 3s-4.36.85-5.94 2.26c-.92.81-1.67 1.8-2.19 2.91-1.45.43-2.56 1.65-2.81 3.17-.04.21-.06.43-.06.66s.02.45.06.66c.25 1.51 1.36 2.74 2.81 3.17.52 1.11 1.27 2.09 2.17 2.89C7.62 20.14 9.71 21 12 21s4.38-.86 5.97-2.28c.9-.8 1.65-1.79 2.17-2.89 1.44-.43 2.55-1.65 2.8-3.17zM19 14c-.1 0-.19-.02-.29-.03-.2.67-.49 1.29-.86 1.86C16.6 17.74 14.45 19 12 19s-4.6-1.26-5.85-3.17c-.37-.57-.66-1.19-.86-1.86-.1.01-.19.03-.29.03-1.1 0-2-.9-2-2s.9-2 2-2c.1 0 .19.02.29.03.2-.67.49-1.29.86-1.86C7.4 6.26 9.55 5 12 5s4.6 1.26 5.85 3.17c.37.57.66 1.19.86 1.86.1-.01.19-.03.29-.03 1.1 0 2 .9 2 2s-.9 2-2 2zM7.5 14c.76 1.77 2.49 3 4.5 3s3.74-1.23 4.5-3h-9z\"/>",
                            Name = "Children",
                            Url = "children"
                        },
                        new
                        {
                            Id = 7,
                            Featured = false,
                            Icon = "<g><rect fill=\"none\" height=\"24\" width=\"24\"/></g><g><g/><g><path d=\"M21,5c-1.11-0.35-2.33-0.5-3.5-0.5c-1.95,0-4.05,0.4-5.5,1.5c-1.45-1.1-3.55-1.5-5.5-1.5S2.45,4.9,1,6v14.65 c0,0.25,0.25,0.5,0.5,0.5c0.1,0,0.15-0.05,0.25-0.05C3.1,20.45,5.05,20,6.5,20c1.95,0,4.05,0.4,5.5,1.5c1.35-0.85,3.8-1.5,5.5-1.5 c1.65,0,3.35,0.3,4.75,1.05c0.1,0.05,0.15,0.05,0.25,0.05c0.25,0,0.5-0.25,0.5-0.5V6C22.4,5.55,21.75,5.25,21,5z M21,18.5 c-1.1-0.35-2.3-0.5-3.5-0.5c-1.7,0-4.15,0.65-5.5,1.5V8c1.35-0.85,3.8-1.5,5.5-1.5c1.2,0,2.4,0.15,3.5,0.5V18.5z\"/><g><path d=\"M17.5,10.5c0.88,0,1.73,0.09,2.5,0.26V9.24C19.21,9.09,18.36,9,17.5,9c-1.7,0-3.24,0.29-4.5,0.83v1.66 C14.13,10.85,15.7,10.5,17.5,10.5z\"/><path d=\"M13,12.49v1.66c1.13-0.64,2.7-0.99,4.5-0.99c0.88,0,1.73,0.09,2.5,0.26V11.9c-0.79-0.15-1.64-0.24-2.5-0.24 C15.8,11.66,14.26,11.96,13,12.49z\"/><path d=\"M17.5,14.33c-1.7,0-3.24,0.29-4.5,0.83v1.66c1.13-0.64,2.7-0.99,4.5-0.99c0.88,0,1.73,0.09,2.5,0.26v-1.52 C19.21,14.41,18.36,14.33,17.5,14.33z\"/></g></g></g>",
                            Name = "Classic",
                            Url = "classic"
                        },
                        new
                        {
                            Id = 8,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M8.1 13.34l2.83-2.83L3.91 3.5c-1.56 1.56-1.56 4.09 0 5.66l4.19 4.18zm6.78-1.81c1.53.71 3.68.21 5.27-1.38 1.91-1.91 2.28-4.65.81-6.12-1.46-1.46-4.2-1.1-6.12.81-1.59 1.59-2.09 3.74-1.38 5.27L3.7 19.87l1.41 1.41L12 14.41l6.88 6.88 1.41-1.41L13.41 13l1.47-1.47z\"/>",
                            Name = "Cooking",
                            Url = "cooking"
                        },
                        new
                        {
                            Id = 9,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M20.57 14.86L22 13.43 20.57 12 17 15.57 8.43 7 12 3.43 10.57 2 9.14 3.43 7.71 2 5.57 4.14 4.14 2.71 2.71 4.14l1.43 1.43L2 7.71l1.43 1.43L2 10.57 3.43 12 7 8.43 15.57 17 12 20.57 13.43 22l1.43-1.43L16.29 22l2.14-2.14 1.43 1.43 1.43-1.43-1.43-1.43L22 16.29z\"/>",
                            Name = "Health & Fitness",
                            Url = "health-fitness"
                        },
                        new
                        {
                            Id = 10,
                            Featured = false,
                            Icon = "<g><rect fill=\"none\" height=\"24\" width=\"24\"/></g><g><path d=\"M12,2C6.49,2,2,6.49,2,12s4.49,10,10,10c1.38,0,2.5-1.12,2.5-2.5c0-0.61-0.23-1.2-0.64-1.67c-0.08-0.1-0.13-0.21-0.13-0.33 c0-0.28,0.22-0.5,0.5-0.5H16c3.31,0,6-2.69,6-6C22,6.04,17.51,2,12,2z M17.5,13c-0.83,0-1.5-0.67-1.5-1.5c0-0.83,0.67-1.5,1.5-1.5 s1.5,0.67,1.5,1.5C19,12.33,18.33,13,17.5,13z M14.5,9C13.67,9,13,8.33,13,7.5C13,6.67,13.67,6,14.5,6S16,6.67,16,7.5 C16,8.33,15.33,9,14.5,9z M5,11.5C5,10.67,5.67,10,6.5,10S8,10.67,8,11.5C8,12.33,7.33,13,6.5,13S5,12.33,5,11.5z M11,7.5 C11,8.33,10.33,9,9.5,9S8,8.33,8,7.5C8,6.67,8.67,6,9.5,6S11,6.67,11,7.5z\"/></g>",
                            Name = "Art",
                            Url = "art"
                        },
                        new
                        {
                            Id = 11,
                            Featured = false,
                            Icon = "<g><rect fill=\"none\" height=\"24\" width=\"24\"/></g><g><path d=\"M19.8,18.4L14,10.67V6.5l1.35-1.69C15.61,4.48,15.38,4,14.96,4H9.04C8.62,4,8.39,4.48,8.65,4.81L10,6.5v4.17L4.2,18.4 C3.71,19.06,4.18,20,5,20h14C19.82,20,20.29,19.06,19.8,18.4z\"/></g>",
                            Name = "Science",
                            Url = "science"
                        },
                        new
                        {
                            Id = 12,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M13.49 5.48c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm-3.6 13.9l1-4.4 2.1 2v6h2v-7.5l-2.1-2 .6-3c1.3 1.5 3.3 2.5 5.5 2.5v-2c-1.9 0-3.5-1-4.3-2.4l-1-1.6c-.4-.6-1-1-1.7-1-.3 0-.5.1-.8.1l-5.2 2.2v4.7h2v-3.4l1.8-.7-1.6 8.1-4.9-1-.4 2 7 1.4z\"/>",
                            Name = "Sport",
                            Url = "sport"
                        },
                        new
                        {
                            Id = 13,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0V0z\" fill=\"none\"/><circle cx=\"15.5\" cy=\"9.5\" r=\"1.5\"/><circle cx=\"8.5\" cy=\"9.5\" r=\"1.5\"/><path d=\"M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm0-6c-2.33 0-4.32 1.45-5.12 3.5h1.67c.69-1.19 1.97-2 3.45-2s2.75.81 3.45 2h1.67c-.8-2.05-2.79-3.5-5.12-3.5z\"/>",
                            Name = "Horror",
                            Url = "horror"
                        },
                        new
                        {
                            Id = 14,
                            Featured = false,
                            Icon = "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z\"/>",
                            Name = "Self-Help",
                            Url = "self-help"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BookWorld",
                            PrimaryColor = "Leaf"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quanity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId", "ProductTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neuromancer is a science fiction novel by American-Canadian writer William Gibson, published in 1984.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4b/Neuromancer_%28Book%29.jpg",
                            Title = "Neuromancer",
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Snow Crash is a science fiction novel by American writer Neal Stephenson, published in 1992.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d5/Snowcrash.jpg",
                            Title = "Snow Crash",
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Foundation is a science fiction novel by American writer Isaac Asimov, first published in 1951.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/25/Foundation_gnome.jpg",
                            Title = "Foundation",
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Brave New World is a dystopian social science fiction novel by English author Aldous Huxley, published in 1932.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/62/BraveNewWorld_FirstEdition.jpg",
                            Title = "Brave New World",
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hyperion is a science fiction novel by American author Dan Simmons, published in 1989.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a1/Hyperion_cover.jpg",
                            Title = "Hyperion",
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ender's Game is a 1985 military science fiction novel by American author Orson Scott Card.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/95/Ender%27s_Game_cover_ISBN_0312932081.jpg",
                            Title = "Ender's Game",
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "The Martian is a 2011 science fiction novel written by Andy Weir.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c3/The_Martian_2014.jpg",
                            Title = "The Martian",
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Left Hand of Darkness is a science fiction novel by U.S. writer Ursula K. Le Guin, published in 1969.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/29/TheLeftHandOfDarkness1stEd.jpg",
                            Title = "The Left Hand of Darkness",
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Stranger in a Strange Land is a 1961 science fiction novel by American author Robert A. Heinlein.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/84/StrangerInaStrangeLand_Cover.jpg",
                            Title = "Stranger in a Strange Land",
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Do Androids Dream of Electric Sheep? is a science fiction novel by American writer Philip K. Dick, published in 1968.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/ee/DoAndroidsDream.png",
                            Title = "Do Androids Dream of Electric Sheep?",
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "The Road is a 2006 novel by American writer Cormac McCarthy. It is a post-apocalyptic story of a father and his young son.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6b/The-road.jpg",
                            Title = "The Road",
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/dc/The_Hunger_Games.jpg",
                            Title = "The Hunger Games",
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ready Player Two is a 2020 science fiction novel by American author Ernest Cline.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/Ready_Player_Two.jpg",
                            Title = "Ready Player Two",
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Fahrenheit 451 is a 1953 dystopian novel by American writer Ray Bradbury.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/db/Fahrenheit_451_1st_ed_cover.jpg",
                            Title = "Fahrenheit 451",
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "The Handmaid's Tale is a dystopian novel by Canadian author Margaret Atwood, published in 1985.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/ba/TheHandmaidsTale.jpg",
                            Title = "The Handmaid's Tale",
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Altered Carbon is a 2002 science fiction novel by the English author Richard K. Morgan.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/b5/Altered_Carbon_%28cover%29.jpg",
                            Title = "Altered Carbon",
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            Description = "Leviathan Wakes is a science fiction novel by James S. A. Corey, the first book in The Expanse series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/03/Leviathan_Wakes.jpg",
                            Title = "The Expanse: Leviathan Wakes",
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            Description = "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg",
                            Title = "The Hobbit",
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            Description = "A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels by American author George R. R. Martin.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/93/AGameOfThrones.jpg",
                            Title = "A Game of Thrones",
                            Views = 0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J.K. Rowling.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg",
                            Title = "Harry Potter and the Philosopher's Stone",
                            Views = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "The Way of Kings is an epic fantasy novel written by American author Brandon Sanderson.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/TheWayOfKings.png",
                            Title = "The Way of Kings",
                            Views = 0
                        },
                        new
                        {
                            Id = 23,
                            Description = "Mistborn: The Final Empire is a fantasy novel written by American author Brandon Sanderson.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6d/Mistborn-cover.jpg",
                            Title = "Mistborn: The Final Empire",
                            Views = 0
                        },
                        new
                        {
                            Id = 24,
                            Description = "The Lies of Locke Lamora is a fantasy novel by American writer Scott Lynch.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4c/The_Lies_of_Locke_Lamora.jpg",
                            Title = "The Lies of Locke Lamora",
                            Views = 0
                        },
                        new
                        {
                            Id = 25,
                            Description = "Uprooted is a fantasy novel written by Naomi Novik.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a7/Uprooted_book_cover.jpg",
                            Title = "Uprooted",
                            Views = 0
                        },
                        new
                        {
                            Id = 26,
                            Description = "Circe is a 2018 novel by American writer Madeline Miller.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4b/Circe-novel.jpg",
                            Title = "Circe",
                            Views = 0
                        },
                        new
                        {
                            Id = 27,
                            Description = "The Night Circus is a fantasy novel by Erin Morgenstern.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a5/TheNightCircus.jpg",
                            Title = "The Night Circus",
                            Views = 0
                        },
                        new
                        {
                            Id = 28,
                            Description = "Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch is a 1990 novel written by Neil Gaiman and Terry Pratchett.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/1d/GoodOmensCover.jpg",
                            Title = "Good Omens",
                            Views = 0
                        },
                        new
                        {
                            Id = 29,
                            Description = "American Gods is a fantasy novel by British author Neil Gaiman.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/American_Gods.jpg",
                            Title = "American Gods",
                            Views = 0
                        },
                        new
                        {
                            Id = 30,
                            Description = "The Ocean at the End of the Lane is a 2013 novel by British author Neil Gaiman.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4e/Ocean_at_the_End_of_the_Lane_US_cover.jpg",
                            Title = "The Ocean at the End of the Lane",
                            Views = 0
                        },
                        new
                        {
                            Id = 31,
                            Description = "The Color of Magic is a 1983 fantasy novel by British writer Terry Pratchett, the first book in his Discworld series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Colour_of_Magic_%28cover_art%29.jpg",
                            Title = "The Color of Magic",
                            Views = 0
                        },
                        new
                        {
                            Id = 32,
                            Description = "Mort is a fantasy novel by British writer Terry Pratchett, the fourth book in his Discworld series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/Mort_%28Terry_Pratchett_novel_-_cover_art%29.jpg",
                            Title = "Mort",
                            Views = 0
                        },
                        new
                        {
                            Id = 33,
                            Description = "Small Gods is the thirteenth of Terry Pratchett's Discworld novels, published in 1992.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8c/Smallgods.jpg",
                            Title = "Small Gods",
                            Views = 0
                        },
                        new
                        {
                            Id = 34,
                            Description = "Guards! Guards! is a fantasy novel by British writer Terry Pratchett, the eighth book in his Discworld series.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/20/Guards-Guards-cover.jpg",
                            Title = "Guards! Guards!",
                            Views = 0
                        },
                        new
                        {
                            Id = 35,
                            Description = "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg",
                            Title = "The Hobbit",
                            Views = 0
                        },
                        new
                        {
                            Id = 36,
                            Description = "The Fellowship of the Ring is the first of three volumes of the epic novel The Lord of the Rings by the English author J. R. R. Tolkien.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif",
                            Title = "The Fellowship of the Ring",
                            Views = 0
                        },
                        new
                        {
                            Id = 37,
                            Description = "The Two Towers is the second volume of J.R.R. Tolkien's high-fantasy novel The Lord of the Rings.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a1/The_Two_Towers_cover.gif",
                            Title = "The Two Towers",
                            Views = 0
                        },
                        new
                        {
                            Id = 38,
                            Description = "The Return of the King is the third and final volume of J.R.R. Tolkien's The Lord of the Rings.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/11/The_Return_of_the_King_cover.gif",
                            Title = "The Return of the King",
                            Views = 0
                        },
                        new
                        {
                            Id = 39,
                            Description = "The Silmarillion is a collection of mythopoeic works by English writer J. R. R. Tolkien, edited and published posthumously by his son, Christopher Tolkien.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/The_Silmarillion_first_edition.jpg",
                            Title = "The Silmarillion",
                            Views = 0
                        },
                        new
                        {
                            Id = 40,
                            Description = "The Catcher in the Rye is a novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/32/Rye_catcher.jpg",
                            Title = "The Catcher in the Rye",
                            Views = 0
                        },
                        new
                        {
                            Id = 41,
                            Description = "To Kill a Mockingbird is a novel by Harper Lee published in 1960.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/7/79/To_Kill_a_Mockingbird.JPG",
                            Title = "To Kill a Mockingbird",
                            Views = 0
                        },
                        new
                        {
                            Id = 42,
                            Description = "Nineteen Eighty-Four, often referred to as 1984, is a dystopian social science fiction novel by the English writer George Orwell.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c3/1984first.jpg",
                            Title = "1984",
                            Views = 0
                        },
                        new
                        {
                            Id = 44,
                            Description = "Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Title_page_of_Pride_and_Prejudice%2C_the_first_edition.jpg/800px-Title_page_of_Pride_and_Prejudice%2C_the_first_edition.jpg",
                            Title = "Pride and Prejudice",
                            Views = 0
                        },
                        new
                        {
                            Id = 45,
                            Description = "Moby-Dick; or, The Whale is an 1851 novel by American writer Herman Melville.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/57/Moby-Dick_FE_title_page.jpg",
                            Title = "Moby-Dick",
                            Views = 0
                        },
                        new
                        {
                            Id = 46,
                            Description = "The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/TheGreatGatsby_1925jacket.jpeg/800px-TheGreatGatsby_1925jacket.jpeg",
                            Title = "The Great Gatsby",
                            Views = 0
                        },
                        new
                        {
                            Id = 47,
                            Description = "War and Peace is a novel by the Russian author Leo Tolstoy, published from 1865 to 1869.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/8b/War-and-peace-book-cover.jpg",
                            Title = "War and Peace",
                            Views = 0
                        },
                        new
                        {
                            Id = 48,
                            Description = "Dune is a science fiction novel by American author Frank Herbert, originally published in 1965.",
                            Featured = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a8/Dune_1965_First_Edition.jpg",
                            Title = "Dune",
                            Views = 0
                        },
                        new
                        {
                            Id = 49,
                            Description = "Jane Eyre is a novel by English writer Charlotte Brontë, published under the pen name \"Currer Bell\", on 16 October 1847.",
                            Featured = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Jane_Eyre_title_page.jpg/800px-Jane_Eyre_title_page.jpg",
                            Title = "Jane Eyre",
                            Views = 0
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductCategories", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 8
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReview");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paperback"
                        },
                        new
                        {
                            Id = 3,
                            Name = "E-Book"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audiobook"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 2,
                            OriginalPrice = 19.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 4,
                            OriginalPrice = 29.99m,
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 2,
                            OriginalPrice = 14.99m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 3.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 2.99m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 2,
                            OriginalPrice = 29.99m,
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 3,
                            OriginalPrice = 24.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductTypeId = 1,
                            OriginalPrice = 299m,
                            Price = 159.99m
                        },
                        new
                        {
                            ProductId = 11,
                            ProductTypeId = 1,
                            OriginalPrice = 399m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = 12,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 13,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 14,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 15,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 16,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 17,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 18,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 19,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 20,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 22,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 23,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 24,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 25,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 26,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 27,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 28,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 29,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 30,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 31,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 32,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 33,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 34,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 35,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 36,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 37,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 38,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 39,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 40,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 41,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 42,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 6.99m
                        },
                        new
                        {
                            ProductId = 44,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 45,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 5.99m
                        },
                        new
                        {
                            ProductId = 46,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 7.99m
                        },
                        new
                        {
                            ProductId = 47,
                            ProductTypeId = 4,
                            OriginalPrice = 0m,
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 48,
                            ProductTypeId = 3,
                            OriginalPrice = 0m,
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 49,
                            ProductTypeId = 2,
                            OriginalPrice = 0m,
                            Price = 8.99m
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.OrderItem", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Author", "Author")
                        .WithMany("Products")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductCategories", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductReview", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.ProductVariant", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorECommerce.Shared.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Author", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
